# Generated by Django 4.1.4 on 2022-12-27 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vmsApp", "0002_visitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=20,
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("address", models.TextField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="vmsApp.departments",
                    ),
                ),
            ],
            options={"verbose_name_plural": "List of Employee Logs",},
        ),
        migrations.DeleteModel(name="Visitors",),
    ]
