# Generated by Django 4.1.4 on 2022-12-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmsApp", "0003_employee_delete_visitors"),
    ]

    operations = [
        migrations.RenameModel(old_name="Employee", new_name="Employees",),
    ]
